"""
Type stubs for robin-sparkless
"""

from typing import List, Dict, Any, Optional, Union
from typing_extensions import Protocol

class SparkSessionBuilder:
    def appName(self, name: str) -> "SparkSessionBuilder": ...
    def master(self, master: str) -> "SparkSessionBuilder": ...
    def config(self, key: str, value: str) -> "SparkSessionBuilder": ...
    def getOrCreate(self) -> "SparkSession": ...

class SparkSession:
    @staticmethod
    def builder() -> SparkSessionBuilder: ...
    @staticmethod
    def getActiveSession() -> Optional["SparkSession"]: ...
    def createDataFrame(self, data: Any, schema: Optional[Any] = None) -> "DataFrame": ...
    def read(self) -> "DataFrameReader": ...
    def sql(self, query: str) -> "DataFrame": ...
    def stop(self) -> None: ...

class DataFrameReader:
    def csv(self, path: str) -> "DataFrame": ...
    def parquet(self, path: str) -> "DataFrame": ...
    def json(self, path: str) -> "DataFrame": ...

class Column:
    def alias(self, name: str) -> "Column": ...
    def isNull(self) -> "Column": ...
    def isNotNull(self) -> "Column": ...
    def like(self, pattern: str) -> "Column": ...

class DataFrame:
    def schema(self) -> "StructType": ...
    def columns(self) -> List[str]: ...
    def count(self) -> int: ...
    def show(self, n: Optional[int] = None, truncate: Optional[bool] = None) -> None: ...
    def collect(self) -> List[Dict[str, Any]]: ...
    def select(self, cols: List[str]) -> "DataFrame": ...
    def filter(self, condition: Union["Column", str]) -> "DataFrame": ...
    def groupBy(self, cols: List[str]) -> "GroupedData": ...
    def join(self, other: "DataFrame", on: str, how: Optional[str] = None) -> "DataFrame": ...
    def sort(self, cols: List[str], ascending: Optional[bool] = None) -> "DataFrame": ...
    def alias(self, name: str) -> "DataFrame": ...
    def __getitem__(self, key: str) -> "Column": ...

class GroupedData:
    def count(self) -> "DataFrame": ...
    def agg(self, exprs: Dict[str, Any]) -> "DataFrame": ...

class StructType:
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> "StructField": ...

class StructField:
    name: str
    nullable: bool

# Functions
def col(name: str) -> Column: ...
def lit(value: Any) -> Column: ...
def count(col: Column) -> Column: ...
def sum(col: Column) -> Column: ...
def avg(col: Column) -> Column: ...
def max(col: Column) -> Column: ...
def min(col: Column) -> Column: ...
def when(condition: Column, value: Any) -> Column: ...
def coalesce(cols: List[Column]) -> Column: ...
