"""Type stub for sparkless._native (PyO3 extension)."""

from typing import Any

class SparklessError(RuntimeError): ...

class PySparkSessionBuilder:
    def app_name(self, name: str) -> PySparkSessionBuilder: ...
    def appName(self, name: str) -> PySparkSessionBuilder: ...
    def master(self, master: str) -> PySparkSessionBuilder: ...
    def config(self, key: str, value: str) -> PySparkSessionBuilder: ...
    def option(self, key: str, value: Any) -> PySparkSessionBuilder: ...
    def get_or_create(self) -> PySparkSession: ...
    def getOrCreate(self) -> PySparkSession: ...

class PySparkSession:
    def create_dataframe(
        self, data: Any, columns: Any = None, *args: Any, **kwargs: Any
    ) -> PyDataFrame: ...
    def create_dataframe_from_rows(
        self,
        rows: Any,
        schema: Any,
        verify_schema: bool = False,
        allow_missing_columns: bool = False,
    ) -> PyDataFrame: ...
    def read(self) -> PyDataFrameReader: ...
    def sql(self, sql_text: str) -> PyDataFrame: ...
    def table(self, name: str) -> PyDataFrame: ...

class PyDataFrame:
    def filter(self, condition: Any) -> PyDataFrame: ...
    def where(self, condition: Any) -> PyDataFrame: ...
    def select(self, *cols: Any) -> PyDataFrame: ...
    def select_expr(self, *exprs: Any) -> PyDataFrame: ...
    def with_column(self, name: str, col: Any) -> PyDataFrame: ...
    def withColumn(self, name: str, col: Any) -> PyDataFrame: ...
    def with_column_renamed(self, old_name: str, new_name: str) -> PyDataFrame: ...
    def with_columns_renamed(self, cols_map: Any) -> PyDataFrame: ...
    def with_columns(self, cols_map: Any) -> PyDataFrame: ...
    def drop(self, *cols: Any, **kwargs: Any) -> PyDataFrame: ...
    def collect(self) -> list: ...
    def count(self) -> int: ...
    def na(self) -> Any: ...
    def fillna(self, value: Any, subset: Any = None) -> PyDataFrame: ...
    def dropna(
        self, how: str = "any", thresh: Any = None, subset: Any = None
    ) -> PyDataFrame: ...
    def join(self, other: Any, on: Any = None, how: str = "inner") -> PyDataFrame: ...
    def sort(self, *cols: Any, **kwargs: Any) -> PyDataFrame: ...
    def orderBy(self, *cols: Any, **kwargs: Any) -> PyDataFrame: ...
    def limit(self, n: int) -> PyDataFrame: ...
    def union(self, other: Any) -> PyDataFrame: ...
    def unionByName(
        self, other: Any, allowMissingColumns: bool = False
    ) -> PyDataFrame: ...
    def union_by_name(
        self, other: Any, allow_missing_columns: bool = False
    ) -> PyDataFrame: ...
    def groupBy(self, *cols: Any) -> PyGroupedData: ...
    def group_by(self, *cols: Any) -> PyGroupedData: ...
    def write(self) -> PyDataFrameWriter: ...
    def pivot(self, pivot_col: str, values: Any = None) -> Any: ...
    def distinct(self) -> PyDataFrame: ...
    def drop_duplicates(self, subset: Any = None, **kwargs: Any) -> PyDataFrame: ...
    def subtract(self, other: Any) -> PyDataFrame: ...
    def intersect(self, other: Any) -> PyDataFrame: ...
    def intersectAll(self, other: Any) -> PyDataFrame: ...
    def schema(self) -> Any: ...
    def columns(self) -> list[str]: ...

class PyColumn:
    @property
    def name(self) -> str: ...
    def alias(self, name: str) -> PyColumn: ...
    def get_udf_call_info(self) -> Any: ...
    def cast(self, type_name: Any) -> PyColumn: ...
    def astype(self, dtype: Any) -> PyColumn: ...
    def try_cast(self, type_name: Any) -> PyColumn: ...
    def __add__(self, other: Any) -> PyColumn: ...
    def __sub__(self, other: Any) -> PyColumn: ...
    def __mul__(self, other: Any) -> PyColumn: ...
    def __pow__(self, other: Any, modulo: Any = None) -> PyColumn: ...
    def __truediv__(self, other: Any) -> PyColumn: ...
    def __mod__(self, other: Any) -> PyColumn: ...
    def __and__(self, other: Any) -> PyColumn: ...
    def __or__(self, other: Any) -> PyColumn: ...
    def __getitem__(self, key: Any) -> PyColumn: ...
    def and_(self, other: PyColumn) -> PyColumn: ...
    def or_(self, other: PyColumn) -> PyColumn: ...
    def multiply(self, other: Any) -> PyColumn: ...

class PyGroupedData:
    def count(self) -> PyDataFrame: ...
    def sum(self, *cols: Any) -> PyDataFrame: ...
    def avg(self, *cols: Any) -> PyDataFrame: ...
    def min(self, *cols: Any) -> PyDataFrame: ...
    def max(self, *cols: Any) -> PyDataFrame: ...
    def agg(self, *exprs: Any) -> PyDataFrame: ...
    def count_distinct(self, value_col: str) -> PyDataFrame: ...
    def collect_list(self, value_col: str) -> PyDataFrame: ...
    def collect_set(self, value_col: str) -> PyDataFrame: ...

class PyDataFrameReader:
    def csv(self, path: str, *args: Any, **kwargs: Any) -> PyDataFrame: ...
    def json(self, path: str, *args: Any, **kwargs: Any) -> PyDataFrame: ...
    def parquet(self, path: str, *args: Any, **kwargs: Any) -> PyDataFrame: ...
    def schema(self, schema: Any) -> PyDataFrameReader: ...
    def option(self, key: str, value: Any) -> PyDataFrameReader: ...

class PyDataFrameWriter:
    def mode(self, mode: str) -> PyDataFrameWriter: ...
    def save(self, path: str) -> None: ...
    def parquet(self, path: str) -> None: ...
    def csv(self, path: str, **kwargs: Any) -> None: ...
    def json(self, path: str) -> None: ...
    def insertInto(self, tableName: str, overwrite: bool = False) -> None: ...

class PyWhenBuilder: ...
class PyThenBuilder: ...
class PyChainedWhenBuilder: ...
class PyExprStr: ...
class PySortOrder: ...
class PyDataFrameNaFunctions: ...
class PyCubeRollupData: ...
class PyPivotedGroupedData: ...
class PyDatabase: ...
class PyTable: ...
class PyRuntimeConfig: ...
class PySparkContext: ...
class PyCatalog: ...
class PyStorage: ...

def spark_session_builder() -> PySparkSessionBuilder: ...
def column(name: str) -> PyColumn: ...
def expr_str(sql: str) -> PyExprStr: ...
def create_udf_column(udf_name: str, columns: list) -> PyColumn: ...
def set_python_udf_executor(callback: Any) -> None: ...
def lit_i64(value: int) -> PyColumn: ...
def lit_str(value: str) -> PyColumn: ...
def lit_bool(value: bool) -> PyColumn: ...
def lit_f64(value: float) -> PyColumn: ...
def lit_null(dtype: str) -> PyColumn: ...
def lit(value: Any) -> PyColumn: ...
def when(condition: Any, value: Any = None) -> PyWhenBuilder: ...
def upper(col: Any) -> PyColumn: ...
def lower(col: Any) -> PyColumn: ...
def substring(column: Any, start: int, length: int | None = None) -> PyColumn: ...
def trim(col: Any) -> PyColumn: ...
def cast(col: Any, type_name: Any) -> PyColumn: ...
def count(col: Any) -> PyColumn: ...
def sum(col: Any) -> PyColumn: ...
def avg(col: Any) -> PyColumn: ...
def min(col: Any) -> PyColumn: ...
def max(col: Any) -> PyColumn: ...
def create_map(columns: Any) -> PyColumn: ...
def concat(*columns: Any) -> PyColumn: ...
def coalesce(*columns: Any) -> PyColumn: ...
def format_string(fmt: str, *columns: Any) -> PyColumn: ...
def greatest(*columns: Any) -> PyColumn: ...
def least(*columns: Any) -> PyColumn: ...
def regexp_replace(column: Any, pattern: str, replacement: str) -> PyColumn: ...
def regexp_extract(column: Any, pattern: str, idx: int = 0) -> PyColumn: ...
def regexp_extract_all(column: Any, pattern: str, group_index: int = 0) -> PyColumn: ...
def regexp_like(column: Any, pattern: str) -> PyColumn: ...
def split(column: Any, pattern: str, limit: int = -1) -> PyColumn: ...
def array_remove(column: Any, value: Any) -> PyColumn: ...
def array_distinct(column: Any) -> PyColumn: ...
def native_array_union(col1: Any, col2: Any) -> PyColumn: ...
def native_array_intersect(col1: Any, col2: Any) -> PyColumn: ...
def native_array_except(col1: Any, col2: Any) -> PyColumn: ...
def native_map_keys(column: Any) -> PyColumn: ...
def native_map_values(column: Any) -> PyColumn: ...
def native_xxhash64(column: Any) -> PyColumn: ...
def native_md5(column: Any) -> PyColumn: ...
def native_sha1(column: Any) -> PyColumn: ...
def native_sha2(column: Any, numBits: int) -> PyColumn: ...
def native_crc32(column: Any) -> PyColumn: ...
def native_base64(column: Any) -> PyColumn: ...
def native_unbase64(column: Any) -> PyColumn: ...
def native_ascii(column: Any) -> PyColumn: ...
def native_hex(column: Any) -> PyColumn: ...
def native_unhex(column: Any) -> PyColumn: ...
def native_bin(column: Any) -> PyColumn: ...
def native_conv(column: Any, fromBase: int, toBase: int) -> PyColumn: ...
def native_format_number(column: Any, d: int) -> PyColumn: ...
def native_lpad(column: Any, len: int, pad: str) -> PyColumn: ...
def native_rpad(column: Any, len: int, pad: str) -> PyColumn: ...
def native_ltrim(column: Any) -> PyColumn: ...
def native_rtrim(column: Any) -> PyColumn: ...
def native_initcap(column: Any) -> PyColumn: ...
def native_soundex(column: Any) -> PyColumn: ...
def native_length(column: Any) -> PyColumn: ...
def native_reverse(column: Any) -> PyColumn: ...
def native_translate(column: Any, matching: str, replace: str) -> PyColumn: ...
def native_instr(column: Any, substr: str) -> PyColumn: ...
def native_locate(substr: str, column: Any, pos: int) -> PyColumn: ...
def native_repeat(column: Any, n: int) -> PyColumn: ...
def native_regexp_extract(column: Any, pattern: str, idx: int) -> PyColumn: ...
def native_add_months(column: Any, months: int) -> PyColumn: ...
def native_months_between(col1: Any, col2: Any, roundOff: bool) -> PyColumn: ...
def native_next_day(column: Any, dayOfWeek: str) -> PyColumn: ...
def native_last_day(column: Any) -> PyColumn: ...
def native_trunc(column: Any, fmt: str) -> PyColumn: ...
def native_date_trunc(fmt: str, column: Any) -> PyColumn: ...
def native_hour(column: Any) -> PyColumn: ...
def native_minute(column: Any) -> PyColumn: ...
def native_second(column: Any) -> PyColumn: ...
def native_quarter(column: Any) -> PyColumn: ...
def native_dayofyear(column: Any) -> PyColumn: ...
def native_weekofyear(column: Any) -> PyColumn: ...
def arrays_overlap(col1: Any, col2: Any) -> PyColumn: ...
def posexplode(column: Any) -> tuple[PyColumn, PyColumn]: ...
def to_timestamp(column: Any, format: str | None = None) -> PyColumn: ...
def to_date(column: Any, format: str | None = None) -> PyColumn: ...
def current_date() -> PyColumn: ...
def current_timestamp() -> PyColumn: ...
def input_file_name() -> PyColumn: ...
def datediff(end: Any, start: Any) -> PyColumn: ...
def unix_timestamp(column: Any = None, format: str | None = None) -> PyColumn: ...
def from_unixtime(column: Any, format: str | None = None) -> PyColumn: ...
def year(column: Any) -> PyColumn: ...
def month(column: Any) -> PyColumn: ...
def dayofmonth(column: Any) -> PyColumn: ...
def dayofweek(column: Any) -> PyColumn: ...
def date_add(column: Any, n: int) -> PyColumn: ...
def date_sub(column: Any, n: int) -> PyColumn: ...
def date_format(column: Any, format: str) -> PyColumn: ...
def length(column: Any) -> PyColumn: ...
def floor(column: Any) -> PyColumn: ...
def ceil(column: Any) -> PyColumn: ...
def round(column: Any, scale: int = 0) -> PyColumn: ...
def abs(column: Any) -> PyColumn: ...
def sqrt(column: Any) -> PyColumn: ...
def log(column: Any) -> PyColumn: ...
def log_with_base(column: Any, base: float) -> PyColumn: ...
def exp(column: Any) -> PyColumn: ...
def pow(column: Any, exp: int | float) -> PyColumn: ...
def signum(column: Any) -> PyColumn: ...
def sin(column: Any) -> PyColumn: ...
def cos(column: Any) -> PyColumn: ...
def tan(column: Any) -> PyColumn: ...
def asin(column: Any) -> PyColumn: ...
def acos(column: Any) -> PyColumn: ...
def atan(column: Any) -> PyColumn: ...
def atan2(y: Any, x: Any) -> PyColumn: ...
def degrees(column: Any) -> PyColumn: ...
def radians(column: Any) -> PyColumn: ...
def ltrim(column: Any) -> PyColumn: ...
def rtrim(column: Any) -> PyColumn: ...
def hour(column: Any) -> PyColumn: ...
def minute(column: Any) -> PyColumn: ...
def second(column: Any) -> PyColumn: ...
def reverse(column: Any) -> PyColumn: ...
def soundex(column: Any) -> PyColumn: ...
def repeat(column: Any, n: int) -> PyColumn: ...
def initcap(column: Any) -> PyColumn: ...
def levenshtein(col1: Any, col2: Any) -> PyColumn: ...
def try_cast(column: Any, type_name: Any) -> PyColumn: ...
def try_add(col1: Any, col2: Any) -> PyColumn: ...
def concat_ws(sep: str, *columns: Any) -> PyColumn: ...
def array(*columns: Any) -> PyColumn: ...
def struct_(*columns: Any) -> PyColumn: ...
def nullif(column: Any, value: Any) -> PyColumn: ...
def nanvl(column: Any, value: Any) -> PyColumn: ...
def isnan(column: Any) -> PyColumn: ...
def array_position(column: Any, value: Any) -> PyColumn: ...
def row_number_window(partition_by: list[str], order_by: list[str]) -> PyColumn: ...
def percent_rank_window(partition_by: list[str], order_by: list[str]) -> PyColumn: ...
def rank_window(partition_by: list[str], order_by: list[str]) -> PyColumn: ...
def dense_rank_window(partition_by: list[str], order_by: list[str]) -> PyColumn: ...
def ntile_window(n: int, partition_by: list[str], order_by: list[str]) -> PyColumn: ...
def lag_window(
    column_name: str,
    offset: int = 1,
    default: Any = None,
    partition_by: list[str] = ...,
    order_by: list[str] = ...,
) -> PyColumn: ...
def lead_window(
    column_name: str,
    offset: int = 1,
    default: Any = None,
    partition_by: list[str] = ...,
    order_by: list[str] = ...,
) -> PyColumn: ...
def column_over_window(
    col_name: str, window_fn: str, partition_by: list[str], order_by: list[str]
) -> PyColumn: ...
def asinh(column: Any) -> PyColumn: ...
def atanh(column: Any) -> PyColumn: ...
def cosh(column: Any) -> PyColumn: ...
def sinh(column: Any) -> PyColumn: ...
def last_day(column: Any) -> PyColumn: ...
def months_between(col1: Any, col2: Any) -> PyColumn: ...
def timestamp_seconds(column: Any) -> PyColumn: ...
def to_utc_timestamp(column: Any, tz: str) -> PyColumn: ...
def approx_count_distinct(column: Any, rsd: float = 0.05) -> PyColumn: ...
def date_trunc(format: str, column: Any) -> PyColumn: ...
def first(column: Any, ignorenulls: bool = False) -> PyColumn: ...
def translate(column: Any, matching: str, replace: str) -> PyColumn: ...
def substring_index(column: Any, delim: str, count: int) -> PyColumn: ...
def crc32(column: Any) -> PyColumn: ...
def xxhash64(column: Any) -> PyColumn: ...
def get_json_object(column: Any, path: str) -> PyColumn: ...
def json_tuple(column: Any, *paths: str) -> PyColumn: ...
def size(column: Any) -> PyColumn: ...
def array_contains(column: Any, value: Any) -> PyColumn: ...
def explode(column: Any) -> PyColumn: ...
def explode_outer(column: Any) -> PyColumn: ...
def count_distinct(*cols: Any) -> PyColumn: ...
def collect_list(column: Any) -> PyColumn: ...
def collect_set(column: Any) -> PyColumn: ...
def named_struct(names: list[str], columns: list) -> PyColumn: ...
