# Read the Docs configuration (v2)
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install MkDocs and theme for reproducible builds
python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
