"""
Type stubs for robin_sparkless (PySpark-like DataFrame API on Polars).
Use for static type checking (mypy, pyright, etc.).
"""

from __future__ import annotations

from typing import Any

# --- Classes ---

class SparkSession:
    @classmethod
    def builder(cls) -> SparkSessionBuilder: ...
    def is_case_sensitive(self) -> bool: ...
    def create_dataframe(
        self,
        data: Any,
        column_names: list[str],
    ) -> DataFrame: ...
    def createDataFrame(
        self,
        data: Any,
        column_names: list[str],
    ) -> DataFrame: ...
    def create_dataframe_from_rows(
        self,
        data: Any,
        schema: list[tuple[str, str]],
    ) -> DataFrame: ...
    def read_csv(self, path: str) -> DataFrame: ...
    def read_parquet(self, path: str) -> DataFrame: ...
    def read_json(self, path: str) -> DataFrame: ...
    def read_delta(self, path: str) -> DataFrame: ...
    def read_delta_version(
        self, path: str, version: int | None = None
    ) -> DataFrame: ...
    def create_or_replace_temp_view(self, name: str, df: DataFrame) -> None: ...
    def table(self, name: str) -> DataFrame: ...
    def sql(self, query: str) -> DataFrame: ...

class SparkSessionBuilder:
    def app_name(self, name: str) -> SparkSessionBuilder: ...
    def master(self, master: str) -> SparkSessionBuilder: ...
    def config(self, key: str, value: str) -> SparkSessionBuilder: ...
    def get_or_create(self) -> SparkSession: ...

class DataFrame:
    def count(self) -> int: ...
    def show(self, n: int | None = None) -> None: ...
    def collect(self) -> list[dict[str, Any]]: ...
    def filter(self, condition: Column) -> DataFrame: ...
    def select(self, cols: list[str]) -> DataFrame: ...
    def select_expr(self, exprs: list[str]) -> DataFrame: ...
    def with_column(self, column_name: str, expr: Column) -> DataFrame: ...
    def with_columns(
        self, mapping: dict[str, Column] | list[tuple[str, Column]]
    ) -> DataFrame: ...
    def with_columns_renamed(
        self,
        mapping: dict[str, str] | list[tuple[str, str]],
    ) -> DataFrame: ...
    def with_column_renamed(self, old: str, new: str) -> DataFrame: ...
    def order_by(
        self,
        cols: list[str],
        ascending: list[bool] | None = None,
    ) -> DataFrame: ...
    def order_by_exprs(self, sort_orders: list[SortOrder]) -> DataFrame: ...
    def group_by(self, cols: list[str]) -> GroupedData: ...
    def limit(self, n: int) -> DataFrame: ...
    def distinct(self, subset: list[str] | None = None) -> DataFrame: ...
    def union(self, other: DataFrame) -> DataFrame: ...
    def union_by_name(self, other: DataFrame) -> DataFrame: ...
    def join(
        self,
        other: DataFrame,
        on: str | list[str],
        how: str = "inner",
    ) -> DataFrame: ...
    def drop(self, *cols: str) -> DataFrame: ...
    def dropna(self, subset: list[str] | None = None) -> DataFrame: ...
    def col_regex(self, pattern: str) -> DataFrame: ...
    def stat(self) -> DataFrameStat: ...
    def na(self) -> DataFrameNa: ...
    def to_pandas(self) -> list[dict[str, Any]]: ...
    def corr(self) -> DataFrame: ...
    def write(self) -> DataFrameWriter: ...

class DataFrameStat:
    def cov(self, col1: str, col2: str) -> float: ...
    def corr(self, col1: str, col2: str) -> float: ...
    def corr_matrix(self) -> DataFrame: ...

class DataFrameNa:
    def fill(self, value: Column) -> DataFrame: ...
    def drop(self, subset: list[str] | None = None) -> DataFrame: ...

class Column:
    def alias(self, name: str) -> Column: ...
    def gt(self, other: Column) -> Column: ...
    def ge(self, other: Column) -> Column: ...
    def lt(self, other: Column) -> Column: ...
    def le(self, other: Column) -> Column: ...
    def eq(self, other: Column) -> Column: ...
    def neq(self, other: Column) -> Column: ...
    def __eq__(self, other: object) -> Column: ...  # type: ignore[override]
    def __ne__(self, other: object) -> Column: ...  # type: ignore[override]
    def __lt__(self, other: Column) -> Column: ...
    def __le__(self, other: Column) -> Column: ...
    def __gt__(self, other: Column) -> Column: ...
    def __ge__(self, other: Column) -> Column: ...
    def __add__(self, other: Column) -> Column: ...
    def __sub__(self, other: Column) -> Column: ...
    def __mul__(self, other: Column) -> Column: ...
    def __truediv__(self, other: Column) -> Column: ...
    def __mod__(self, other: Column) -> Column: ...
    def __and__(self, other: Column) -> Column: ...
    def __or__(self, other: Column) -> Column: ...
    def map_concat(self, other: Column) -> Column: ...

class SortOrder: ...

class WhenBuilder:
    def when(self, condition: Column) -> ThenBuilder: ...
    def otherwise(self, value: Column) -> Column: ...

class ThenBuilder:
    def then(self, value: Column) -> WhenBuilder: ...
    def otherwise(self, value: Column) -> Column: ...

class GroupedData:
    def count(self) -> DataFrame: ...
    def sum(self, column: str) -> DataFrame: ...
    def avg(self, column: str) -> DataFrame: ...
    def min(self, column: str) -> DataFrame: ...
    def max(self, column: str) -> DataFrame: ...
    def agg(self, exprs: list[Column]) -> DataFrame: ...
    def collect_list(self, column: str) -> DataFrame: ...
    def collect_set(self, column: str) -> DataFrame: ...
    def count_if(self, column: str) -> DataFrame: ...
    def any_value(self, column: str) -> DataFrame: ...
    def bool_and(self, column: str) -> DataFrame: ...
    def bool_or(self, column: str) -> DataFrame: ...
    def product(self, column: str) -> DataFrame: ...
    def kurtosis(self, column: str) -> DataFrame: ...
    def skewness(self, column: str) -> DataFrame: ...

class CubeRollupData:
    def agg(self, exprs: list[Column]) -> DataFrame: ...

class DataFrameWriter:
    def mode(self, mode: str) -> DataFrameWriter: ...
    def format(self, format: str) -> DataFrameWriter: ...
    def save(self, path: str) -> None: ...

# --- Module-level functions (expression builders return Column) ---

def col(name: str) -> Column: ...
def lit(value: None | int | float | bool | str) -> Column: ...
def when(condition: Column) -> ThenBuilder: ...
def coalesce(*cols: Column) -> Column: ...
def sum(column: Column) -> Column: ...
def avg(column: Column) -> Column: ...
def min(column: Column) -> Column: ...
def max(column: Column) -> Column: ...
def count(column: Column) -> Column: ...
def execute_plan(
    data: Any,
    schema: list[tuple[str, str]],
    plan_json: str,
) -> DataFrame: ...

# Unary column functions (column -> Column)
def ascii(column: Column) -> Column: ...
def base64(column: Column) -> Column: ...
def unbase64(column: Column) -> Column: ...
def cast(column: Column, dtype: str) -> Column: ...
def try_cast(column: Column, dtype: str) -> Column: ...
def isnull(column: Column) -> Column: ...
def isnotnull(column: Column) -> Column: ...
def isnan(column: Column) -> Column: ...
def asc(column: Column) -> SortOrder: ...
def asc_nulls_first(column: Column) -> SortOrder: ...
def asc_nulls_last(column: Column) -> SortOrder: ...
def desc(column: Column) -> SortOrder: ...
def desc_nulls_first(column: Column) -> SortOrder: ...
def desc_nulls_last(column: Column) -> SortOrder: ...

# Binary / variadic (common patterns; others follow same style)
def greatest(*columns: Column) -> Column: ...
def least(*columns: Column) -> Column: ...
def add_months(column: Column, n: int) -> Column: ...
def substring(column: Column, pos: int, len: int) -> Column: ...
def overlay(src: Column, replace: Column, pos: int, len: int = -1) -> Column: ...
def format_number(column: Column, d: int) -> Column: ...
def format_string(fmt: str, *columns: Column) -> Column: ...
def concat(*columns: Column) -> Column: ...
def concat_ws(sep: str, *columns: Column) -> Column: ...
def array(*columns: Column) -> Column: ...
def struct(*columns: Column) -> Column: ...
def named_struct(*name_column_pairs: Any) -> Column: ...
def create_map(*key_value_columns: Column) -> Column: ...
def map_concat(a: Column, b: Column) -> Column: ...
def equal_null(a: Column, b: Column) -> Column: ...
def get(column: Column, key: Any) -> Column: ...
def isin(column: Column, values: Any) -> Column: ...
def rand(seed: int | None = None) -> Column: ...
def randn(seed: int | None = None) -> Column: ...

# Placeholder for remaining 200+ expression functions (same pattern: Column in, Column out)
def acos(column: Column) -> Column: ...
def acosh(column: Column) -> Column: ...
def asin(column: Column) -> Column: ...
def asinh(column: Column) -> Column: ...
def atan(column: Column) -> Column: ...
def atan2(y: Column, x: Column) -> Column: ...
def atanh(column: Column) -> Column: ...
def sin(column: Column) -> Column: ...
def cos(column: Column) -> Column: ...
def tan(column: Column) -> Column: ...
def sinh(column: Column) -> Column: ...
def cosh(column: Column) -> Column: ...
def tanh(column: Column) -> Column: ...
def degrees(column: Column) -> Column: ...
def radians(column: Column) -> Column: ...
def cbrt(column: Column) -> Column: ...
def ceiling(column: Column) -> Column: ...
def floor(column: Column) -> Column: ...
def exp(column: Column) -> Column: ...
def expm1(column: Column) -> Column: ...
def ln(column: Column) -> Column: ...
def log10(column: Column) -> Column: ...
def log1p(column: Column) -> Column: ...
def log2(column: Column) -> Column: ...
def power(base: Column, exp: Column) -> Column: ...
def rint(column: Column) -> Column: ...
def round(column: Column, scale: int = 0) -> Column: ...
def signum(column: Column) -> Column: ...
def sqrt(column: Column) -> Column: ...
def left(column: Column, n: int) -> Column: ...
def right(column: Column, n: int) -> Column: ...
def length(column: Column) -> Column: ...
def lower(column: Column) -> Column: ...
def upper(column: Column) -> Column: ...
def ltrim(column: Column) -> Column: ...
def rtrim(column: Column) -> Column: ...
def trim(column: Column) -> Column: ...
def reverse(column: Column) -> Column: ...
def repeat(column: Column, n: int) -> Column: ...
def replace(src: Column, search: str, replacement: str) -> Column: ...
def contains(column: Column, literal: str) -> Column: ...
def startswith(column: Column, literal: str) -> Column: ...
def endswith(column: Column, literal: str) -> Column: ...
def like(column: Column, pattern: str) -> Column: ...
def ilike(column: Column, pattern: str) -> Column: ...
def rlike(column: Column, pattern: str) -> Column: ...
def regexp_extract(column: Column, pattern: str, idx: int = 0) -> Column: ...
def regexp_replace(column: Column, pattern: str, replacement: str) -> Column: ...
def split(column: Column, pattern: str) -> Column: ...
def substring_index(column: Column, delim: str, count: int) -> Column: ...
def chr(column: Column) -> Column: ...
def char(column: Column) -> Column: ...
def md5(column: Column) -> Column: ...
def sha1(column: Column) -> Column: ...
def sha2(column: Column, numBits: int) -> Column: ...
def dayofmonth(column: Column) -> Column: ...
def dayofweek(column: Column) -> Column: ...
def dayofyear(column: Column) -> Column: ...
def hour(column: Column) -> Column: ...
def minute(column: Column) -> Column: ...
def month(column: Column) -> Column: ...
def quarter(column: Column) -> Column: ...
def second(column: Column) -> Column: ...
def weekofyear(column: Column) -> Column: ...
def year(column: Column) -> Column: ...
def date_add(column: Column, days: int) -> Column: ...
def date_sub(column: Column, days: int) -> Column: ...
def datediff(end: Column, start: Column) -> Column: ...
def months_between(end: Column, start: Column) -> Column: ...
def to_date(column: Column) -> Column: ...
def to_timestamp(column: Column) -> Column: ...
def unix_timestamp(column: Column, fmt: str | None = None) -> Column: ...
def from_unixtime(column: Column, fmt: str = "yyyy-MM-dd HH:mm:ss") -> Column: ...
def current_timestamp() -> Column: ...
def current_date() -> Column: ...
def date_format(column: Column, fmt: str) -> Column: ...
def nvl(column: Column, replacement: Column) -> Column: ...
def nvl2(column: Column, if_not_null: Column, if_null: Column) -> Column: ...
def ifnull(column: Column, replacement: Column) -> Column: ...
def array_contains(column: Column, value: Any) -> Column: ...
def array_distinct(column: Column) -> Column: ...
def array_except(a: Column, b: Column) -> Column: ...
def array_intersect(a: Column, b: Column) -> Column: ...
def array_join(
    column: Column, delimiter: str, null_replacement: str | None = None
) -> Column: ...
def array_max(column: Column) -> Column: ...
def array_min(column: Column) -> Column: ...
def array_position(column: Column, value: Any) -> Column: ...
def array_remove(column: Column, value: Any) -> Column: ...
def array_sort(column: Column) -> Column: ...
def array_union(a: Column, b: Column) -> Column: ...
def arrays_zip(*columns: Column) -> Column: ...
def explode(column: Column) -> Column: ...
def explode_outer(column: Column) -> Column: ...
def posexplode(column: Column) -> Column: ...
def size(column: Column) -> Column: ...
def slice(column: Column, start: int, length: int) -> Column: ...
def sort_array(column: Column, asc: bool = True) -> Column: ...
def element_at(column: Column, idx: int) -> Column: ...
def map_keys(column: Column) -> Column: ...
def map_values(column: Column) -> Column: ...
def map_contains_key(column: Column, key: Any) -> Column: ...
def row_number() -> Column: ...
def rank() -> Column: ...
def dense_rank() -> Column: ...
def ntile(n: int) -> Column: ...
def broadcast(df: DataFrame) -> DataFrame: ...
def input_file_name() -> Column: ...
def monotonically_increasing_id() -> Column: ...
def spark_partition_id() -> Column: ...
def version() -> Column: ...
def current_user() -> Column: ...
def user() -> Column: ...
def hash(*columns: Column) -> Column: ...
def crc32(column: Column) -> Column: ...
def xxhash64(*columns: Column) -> Column: ...
def assert_true(column: Column) -> Column: ...
def raise_error(column: Column) -> Column: ...
def bitwiseNOT(column: Column) -> Column: ...
def bitwise_not(column: Column) -> Column: ...
def bit_count(column: Column) -> Column: ...
def bit_get(column: Column, bit: int) -> Column: ...
def getbit(column: Column, bit: int) -> Column: ...
def shiftleft(column: Column, n: int) -> Column: ...
def shiftright(column: Column, n: int) -> Column: ...
def shift_left(column: Column, n: int) -> Column: ...
def shift_right(column: Column, n: int) -> Column: ...
def typeof(column: Column) -> Column: ...
def bround(column: Column, scale: int = 0) -> Column: ...
def negate(column: Column) -> Column: ...
def positive(column: Column) -> Column: ...
def cot(column: Column) -> Column: ...
def csc(column: Column) -> Column: ...
def sec(column: Column) -> Column: ...
def e() -> Column: ...
def pi() -> Column: ...
def median(column: Column) -> Column: ...
def mode(column: Column) -> Column: ...
def stddev_pop(column: Column) -> Column: ...
def var_pop(column: Column) -> Column: ...
def count_distinct(column: Column) -> Column: ...
def approx_count_distinct(column: Column) -> Column: ...
def first(column: Column) -> Column: ...
def last(column: Column) -> Column: ...
def collect_list(column: Column) -> Column: ...
def collect_set(column: Column) -> Column: ...
